import type { Locale, NewsItem, ProductNode, ProductProfile } from "./types";

export const copy = {
  en: {
    nav: {
      home: "Home",
      about: "About Us",
      products: "Products",
      quality: "Quality Assurance",
      news: "Industry Insights",
      contact: "Contact Us",
    },
    hero: {
      title: "OEM / ODM outdoor gear supplier for camping brands.",
      body: "We provide quality-checked camping and outdoor gear with flexible OEM/ODM solutions, strict quality control, and reliable supply support for global camping brands, wholesalers, and retailers.",
      primaryCta: "Explore Categories",
      secondaryCta: "Send Inquiry",
      points: ["10+ outdoor categories", "OEM / ODM development", "Inspection before shipment"],
    },
    featuredProducts: {
      eyebrow: "",
      title: "Featured Outdoor Gear",
      body: "",
      cta: "View All Products",
      items: [
        {
          name: "Trekking Poles",
          description: "Lightweight support for hiking, trekking, and long-distance outdoor travel.",
          highlight: "Portable / export-friendly",
          href: "/products/trekking-poles",
          imageUrl: "/images/products/trekking-poles-product.webp",
        },
        {
          name: "Camping Wagons",
          description: "Foldable hauling solutions for campsites, beaches, gardens, and family trips.",
          highlight: "High demand / practical utility",
          href: "/products/camping-wagons",
          imageUrl: "/images/products/camping-wagons-studio.webp",
        },
        {
          name: "Folding Camping Chairs",
          description: "Comfort-focused seating built for leisure camping, events, and retail programs.",
          highlight: "Core furniture line",
          href: "/products/folding-camping-chairs",
          imageUrl: "/images/products/folding-camping-chairs-studio.webp",
        },
        {
          name: "Hard Cooler Boxes",
          description: "Rugged chilled storage for campsites, picnics, and road-trip assortments.",
          highlight: "Utility anchor",
          href: "/products/hard-cooler-boxes",
          imageUrl: "/images/products/hard-cooler-boxes-studio.webp",
        },
        {
          name: "Inflatable Sleeping Pads",
          description: "Comfortable sleep support for car camping, family trips, and compact outdoor kits.",
          highlight: "Sleep system",
          href: "/products/inflatable-sleeping-pads",
          imageUrl: "/images/products/inflatable-sleeping-pads-studio.webp",
        },
        {
          name: "Camping Cots",
          description: "Elevated sleeping solutions that stay stable, pack down neatly, and suit retail programs.",
          highlight: "Camp sleep",
          href: "/products/camping-cots",
          imageUrl: "/images/products/camping-cots-studio.webp",
        },
        {
          name: "Camping Tarps",
          description: "Flexible shade and rain coverage for campsite layouts, events, and outdoor assortments.",
          highlight: "Shelter line",
          href: "/products/camping-tarps",
          imageUrl: "/images/products/camping-tarps-studio.webp",
        },
        {
          name: "Folding Camping Tables",
          description: "Compact camp tables for outdoor dining, coffee setups, and practical kitchen bundles.",
          highlight: "Camp kitchen",
          href: "/products/folding-camping-tables",
          imageUrl: "/images/products/folding-camping-tables-studio.webp",
        },
      ],
    },
    homeSourcing: {
      title: "A calmer path from sample to shipment.",
      body: "We provide quality-checked camping and outdoor gear with flexible OEM/ODM solutions, strict quality control, and reliable supply support for global camping brands, wholesalers, and retailers.",
      cta: "Discuss Your Order",
      steps: [
        {
          label: "Before production",
          title: "Sample alignment",
          body: "Materials, color, packaging, and target cost are confirmed before the order moves forward.",
        },
        {
          label: "During production",
          title: "Visible checkpoints",
          body: "Key requirements stay clear while production, packing, and inspection points are coordinated.",
        },
        {
          label: "Before handoff",
          title: "Export-ready delivery",
          body: "Final checks, cartons, documents, and shipment details are prepared for buyer review.",
        },
      ],
      gallery: [
        {
          imageUrl: "/images/about/factory-inspection.png",
          alt: "Factory worker inspecting outdoor fabric",
          caption: "Sample and material checks",
        },
        {
          imageUrl: "/images/about/factory-sewing.png",
          alt: "Factory sewing line producing outdoor bags",
          caption: "Controlled production line",
        },
        {
          imageUrl: "/images/about/factory-packing.png",
          alt: "Factory team packing outdoor products for shipment",
          caption: "Packing for export handoff",
        },
      ],
    },
    qualityService: {
      title: "After-sales support follows a clear service-desk flow.",
      body: "Inspired by membership-style service processes, each case is received, reviewed, resolved, and followed up against the same order record, so overseas buyers can see where the after-sales request stands.",
      cta: "Contact the Team",
      assurances: [
        {
          title: "Submit the request",
          body: "The buyer shares the order number, product model, issue description, photos or videos, and the preferred handling direction.",
          imageUrl: "/images/service/after-sales-intake.png",
          alt: "After-sales service intake desk with order records and issue evidence",
        },
        {
          title: "Service review",
          body: "Our team checks whether the case matches the agreed scope, then reviews batch records, packing details, and inspection notes.",
          imageUrl: "/images/service/after-sales-review.png",
          alt: "After-sales service team reviewing issue evidence and batch records",
        },
        {
          title: "Confirm the option",
          body: "A practical solution is confirmed with the buyer, such as parts, replacement goods, replenishment, repair guidance, or credit discussion.",
          imageUrl: "/images/service/after-sales-fulfillment.png",
          alt: "Replacement parts prepared for an after-sales service solution",
        },
        {
          title: "Close and follow up",
          body: "After the action is completed, the result is recorded for buyer review and future production, packing, and inspection improvement.",
          imageUrl: "/images/service/after-sales-follow-up.png",
          alt: "After-sales case follow-up and closure records on an office desk",
        },
      ],
      responseSteps: [
        {
          title: "Identify the issue",
          body: "Collect photos, order details, batch information, and buyer feedback so the case is clear before action is taken.",
        },
        {
          title: "Confirm responsibility",
          body: "Review production, packing, inspection, and shipping context to understand where the issue most likely occurred.",
        },
        {
          title: "Provide a solution",
          body: "Coordinate replacement parts, replenishment, repair guidance, credit discussion, or process correction for the next order.",
        },
      ],
    },
    newsletter: {
      title: "Get Updates & Exclusive Offers",
      body: "Subscribe for product updates and exclusive discounts.",
      emailLabel: "Email address",
      placeholder: "enter your email address",
      submit: "Submit",
      success: "Thanks. We will keep you updated.",
    },
    trekkingPole: {
      eyebrow: "TP-AL-001",
      title: "Aluminum Alloy Trekking Poles",
      subtitle: "A lightweight beginner-friendly trekking pole set built for stable support on everyday hiking routes.",
      primaryCta: "Request Quote",
      secondaryCta: "View Specifications",
      backToProducts: "Back to Products",
      highlights: [
        "Approx. 259 g each",
        "51–110 cm adjustable length",
        "4-section telescopic storage",
        "Hidden internal lock",
      ],
      featureTitle: "Designed for easy, confident hiking.",
      featureBody:
        "TP-AL-001 balances portability, simple adjustment, and durable everyday materials for first-time hikers, retail programs, and outdoor starter kits.",
      specsTitle: "Product Details",
      specs: [
        { label: "Material", value: "Aluminum alloy shaft" },
        { label: "Handle", value: "TPR straight handle" },
        { label: "Tip", value: "Carbon steel" },
        { label: "Best use", value: "Beginner hiking" },
        { label: "Included", value: "Mud basket + tip protector" },
        { label: "Pack", value: "Set of 2" },
      ],
    },
    about: {
      eyebrow: "About Us",
      title: "Built for dependable sourcing.",
      body: "Dawnrise Camp works with overseas buyers on camping gear development, stable production, and export-ready fulfillment.",
      cta: "Watch Company Video",
      videoError: "Company video will appear here after the R2 asset is uploaded.",
      features: ["OEM / ODM Support", "Quality Inspection", "Global Shipping"],
      introSections: [
        {
          title: "Company Introduction",
          body: "DawnRiseCamp is a professional outdoor products brand dedicated to reliable camping, hiking, and adventure gear for global customers.\nWith years of overseas supply experience, strict quality control, and secondary inspection before shipment, we provide dependable outdoor products and flexible OEM/ODM solutions for wholesalers, distributors, retailers, and e-commerce sellers worldwide.",
          imageUrl: "/images/about/company-introduction.png",
          imageAlt: "Camping and outdoor gear samples prepared for inspection and export",
        },
        {
          title: "Brand Mission & Service Philosophy",
          body: "Our mission is to provide practical, durable, and reliable outdoor products for global customers. We focus on real outdoor use, stable quality, responsive service, and long-term cooperation with our business partners.",
          imageUrl: "/images/about/brand-mission.png",
          imageAlt: "Outdoor service planning desk with camping gear and mountain campsite view",
        },
        {
          title: "OEM / ODM Service",
          body: "We support OEM and ODM services, including logo customization, packaging design, color options, material selection, size adjustment, and product combination solutions. Whether you are a wholesaler, distributor, retailer, or e-commerce seller, we can help you build customized outdoor product solutions for your market.",
          imageUrl: "/images/about/oem-odm-service.png",
          imageAlt: "Outdoor product development workbench with materials, packaging, and color swatches",
        },
      ],
      qualificationsEyebrow: "Certification",
      qualificationsTitle: "Company qualifications",
      qualificationsBody:
        "Qualification files are organized for buyer review, factory evaluation, and channel onboarding.",
      qualifications: [
        {
          title: "Business license",
          body: "Core registration information and operating scope prepared for partner due diligence.",
          imageUrl: "/images/about/qualifications/business-license.png",
          imageAlt: "Abstract business license document thumbnail",
          badge: "Verified",
          updatedLabel: "Updated",
          availability: "Available for buyer review",
        },
        {
          title: "Export records",
          body: "Export-ready documentation support for customs, shipping, and overseas buyer review.",
          imageUrl: "/images/about/qualifications/export-records.png",
          imageAlt: "Abstract export records document thumbnail",
          badge: "Verified",
          updatedLabel: "Updated",
          availability: "Available for buyer review",
        },
        {
          title: "Factory coordination",
          body: "Supplier and production information can be matched to the product line and order requirements.",
          imageUrl: "/images/about/qualifications/factory-coordination.png",
          imageAlt: "Abstract factory coordination file thumbnail",
          badge: "Verified",
          updatedLabel: "Updated",
          availability: "Available for buyer review",
        },
      ],
      qualificationsPanel: {
        title: "Buyer review pack",
        body: "Core qualification files are grouped so buyers can review company status, export readiness, and supplier coordination before moving into sampling or bulk orders.",
        items: ["Company registration", "Export handoff records", "Supplier coordination notes"],
      },
      reportsEyebrow: "Reports",
      reportsTitle: "Testing reports",
      reportsBody:
        "Product-specific reports can be prepared or updated according to buyer markets, materials, and platform requirements.",
      reports: [
        {
          label: "Material",
          title: "Material and fabric checks",
          body: "Fabric, coating, color fastness, and key material checks are arranged by product category.",
          imageUrl: "/images/about/reports/material-fabric-checks.png",
          imageAlt: "Abstract material and fabric testing report thumbnail",
        },
        {
          label: "Safety",
          title: "Structure and load testing",
          body: "Load, stability, assembly, and repeated-use checks support camping furniture and gear programs.",
          imageUrl: "/images/about/reports/structure-load-testing.png",
          imageAlt: "Abstract structure and load testing report thumbnail",
        },
        {
          label: "Market",
          title: "Market compliance support",
          body: "Reports can be aligned with the destination market and platform entry requirements before shipment.",
          imageUrl: "/images/about/reports/market-compliance-support.png",
          imageAlt: "Abstract market compliance report thumbnail",
        },
      ],
    },
    quality: {
      eyebrow: "Quality Assurance",
      title: "Strictly Checked. Ready for Adventure.",
      subtitle:
        "Every product is inspected again after production and approved for shipment only when it meets DawnRiseCamp brand standards.",
      processTitle: "Quality Control Process",
      reportsTitle: "Secondary Inspection Reports",
      qualificationsTitle: "Company Qualifications",
      process: [
        {
          title: "Material Review",
          body: "Check fabrics, frames, hardware, coatings, and core components against the confirmed order requirements.",
        },
        {
          title: "Production Check",
          body: "Monitor workmanship, assembly details, sizing, and packing consistency during the production stage.",
        },
        {
          title: "Secondary Inspection",
          body: "Inspect finished goods again after production before the batch is approved for shipment.",
        },
        {
          title: "Report Record",
          body: "Organize inspection notes, photos, and issue records so buyers can review the shipment status clearly.",
        },
        {
          title: "Shipment Approval",
          body: "Release goods only when the product, packaging, and order details meet DawnRiseCamp standards.",
        },
      ],
      reports: [
        {
          label: "Material",
          title: "Material and fabric checks",
          body: "Fabric, coating, color fastness, and key material checks are arranged by product category.",
          imageUrl: "/images/about/reports/material-fabric-checks.png",
          imageAlt: "Abstract material and fabric testing report thumbnail",
        },
        {
          label: "Safety",
          title: "Structure and load testing",
          body: "Load, stability, assembly, and repeated-use checks support camping furniture and gear programs.",
          imageUrl: "/images/about/reports/structure-load-testing.png",
          imageAlt: "Abstract structure and load testing report thumbnail",
        },
        {
          label: "Market",
          title: "Market compliance support",
          body: "Reports can be aligned with the destination market and platform entry requirements before shipment.",
          imageUrl: "/images/about/reports/market-compliance-support.png",
          imageAlt: "Abstract market compliance report thumbnail",
        },
      ],
      qualifications: [
        {
          title: "Business license",
          body: "Core registration information and operating scope prepared for partner due diligence.",
          imageUrl: "/images/about/qualifications/business-license.png",
          imageAlt: "Abstract business license document thumbnail",
          badge: "Verified",
        },
        {
          title: "Export records",
          body: "Export-ready documentation support for customs, shipping, and overseas buyer review.",
          imageUrl: "/images/about/qualifications/export-records.png",
          imageAlt: "Abstract export records document thumbnail",
          badge: "Verified",
        },
        {
          title: "Factory coordination",
          body: "Supplier and production information can be matched to the product line and order requirements.",
          imageUrl: "/images/about/qualifications/factory-coordination.png",
          imageAlt: "Abstract factory coordination file thumbnail",
          badge: "Verified",
        },
      ],
    },
    products: {
      eyebrow: "Products",
      title: "Product Categories",
      cta: "Request Catalog",
      productLinesLabel: "Product categories",
      partOfLabel: "Part of",
      searchPlaceholder: "Search products or categories",
      noResults: "No matching products found.",
      genericSubtitle:
        "A reliable outdoor product line built for buyer programs, retail assortments, and export-ready sourcing.",
      genericPrimaryCta: "Request Quote",
      genericBackCta: "Back to Products",
    },
    news: {
      eyebrow: "Industry Insights",
      title: "Outdoor product insights and sourcing notes.",
      readMore: "Read More",
      backToNews: "Back to insights",
    },
    contact: {
      eyebrow: "Contact Us",
      title: "We Want to Hear From You",
      body: "Whether you are developing a new outdoor product, comparing suppliers, or preparing a bulk order, our team is available to help. All inquiries will be responded to within 24 hours.",
      emailLabel: "Email",
      phoneLabel: "Phone",
      phone: "+86 571 8888 6688",
      addressLabel: "Office",
      address: "No. 88 Yunhe Road, Yuhang District, Hangzhou, Zhejiang, China",
      hoursLabel: "Business Hours",
      hours: "Mon–Fri · 09:00–18:00",
      supportItems: [
        { title: "Product Consultation", note: "Please send email to", email: "sales@dawnrisecamp.com" },
        { title: "Order Support", note: "Please send email to", email: "sales@dawnrisecamp.com" },
        { title: "Business Inquiry", note: "Please send email to", email: "sales@dawnrisecamp.com" },
      ],
      mapTitle: "Visit Dawnrise Camp",
      mapCta: "Open map",
      name: "Name",
      email: "Email",
      company: "Company",
      message: "Describe Your Request In Detail",
      submit: "Send Inquiry",
      submitting: "Sending...",
      success: "Inquiry sent. We will get back to you soon.",
      error: "Something went wrong. Please try again.",
    },
    footer: {
      promise: "Reliable outdoor products for global buyers.",
    },
  },
  zh: {
    nav: {
      home: "首页",
      about: "关于我们",
      products: "产品",
      quality: "品质保障",
      news: "行业洞察",
      contact: "联系我们",
    },
    hero: {
      title: "面向露营品牌的 OEM / ODM 户外装备供应商。",
      body: "覆盖露营家具、徒步装备、拖车、保温箱和遮蔽类产品，支持打样、验货与出口交付。",
      primaryCta: "查看产品分类",
      secondaryCta: "发送询盘",
      points: ["10+ 户外品类", "OEM / ODM 开发", "出货前验货"],
    },
    featuredProducts: {
      eyebrow: "",
      title: "精选户外产品",
      body: "",
      cta: "查看全部产品",
      items: [
        {
          name: "登山杖",
          description: "适合徒步、登山与长距离户外出行的轻量支撑装备。",
          highlight: "便携 / 易出口",
          href: "/products/trekking-poles",
          imageUrl: "/images/products/trekking-poles-product.webp",
        },
        {
          name: "露营拖车",
          description: "适用于营地、海滩、庭院和家庭出游的折叠运输产品。",
          highlight: "需求高 / 实用性强",
          href: "/products/camping-wagons",
          imageUrl: "/images/products/camping-wagons-studio.webp",
        },
        {
          name: "折叠露营椅",
          description: "面向休闲露营、活动场景和零售渠道的舒适坐具。",
          highlight: "家具主力线",
          href: "/products/folding-camping-chairs",
          imageUrl: "/images/products/folding-camping-chairs-studio.webp",
        },
        {
          name: "硬壳保温箱",
          description: "适用于露营、野餐与自驾组合的耐用储冷产品。",
          highlight: "实用核心款",
          href: "/products/hard-cooler-boxes",
          imageUrl: "/images/products/hard-cooler-boxes-studio.webp",
        },
        {
          name: "充气睡垫",
          description: "适合自驾露营、家庭出行和轻量装备组合的舒适睡眠产品。",
          highlight: "睡眠系统",
          href: "/products/inflatable-sleeping-pads",
          imageUrl: "/images/products/inflatable-sleeping-pads-studio.webp",
        },
        {
          name: "露营行军床",
          description: "离地睡眠更稳定，收纳更规整，适合零售和组合采购项目。",
          highlight: "营地睡眠",
          href: "/products/camping-cots",
          imageUrl: "/images/products/camping-cots-studio.webp",
        },
        {
          name: "露营天幕",
          description: "适用于遮阳、防雨和多种营地布局的户外遮蔽产品。",
          highlight: "遮蔽产品",
          href: "/products/camping-tarps",
          imageUrl: "/images/products/camping-tarps-studio.webp",
        },
        {
          name: "折叠露营桌",
          description: "适合营地用餐、咖啡冲煮和户外厨房组合的便携桌具。",
          highlight: "营地厨房",
          href: "/products/folding-camping-tables",
          imageUrl: "/images/products/folding-camping-tables-studio.webp",
        },
      ],
    },
    homeSourcing: {
      title: "从样品到出货，让链路更清晰。",
      body: "我们为全球露营品牌、批发商和零售商提供经过品质复检的露营与户外装备，支持灵活 OEM / ODM 定制、严格质量控制和稳定供货服务。",
      cta: "沟通您的订单",
      steps: [
        {
          label: "量产前",
          title: "样品确认",
          body: "材质、颜色、包装和目标成本先对齐，再进入订单执行。",
        },
        {
          label: "生产中",
          title: "节点可见",
          body: "围绕生产、包装和验货节点协调，减少过程中的不确定。",
        },
        {
          label: "交接前",
          title: "出货准备",
          body: "完成最终检查、装箱信息、单证和运输细节，方便买家复核。",
        },
      ],
      gallery: [
        {
          imageUrl: "/images/about/factory-inspection.png",
          alt: "工厂人员检查户外面料",
          caption: "样品与材料检查",
        },
        {
          imageUrl: "/images/about/factory-sewing.png",
          alt: "工厂缝制户外包袋",
          caption: "生产过程协调",
        },
        {
          imageUrl: "/images/about/factory-packing.png",
          alt: "工厂团队进行出货包装",
          caption: "出货包装交接",
        },
      ],
    },
    qualityService: {
      title: "售后支持按服务台流程推进。",
      body: "参考会员制零售的服务体验，每个售后事项都围绕同一条订单记录完成受理、核验、方案确认与跟进，让海外买家清楚看到售后请求走到哪一步。",
      cta: "联系团队",
      assurances: [
        {
          title: "提交售后申请",
          body: "客户提供订单号、产品型号、问题描述、图片或视频，并说明希望优先处理的方向。",
          imageUrl: "/images/service/after-sales-intake.png",
          alt: "售后服务受理桌面，包含订单记录与问题证据",
        },
        {
          title: "服务核验",
          body: "团队先判断事项是否符合约定范围，再核对批次记录、包装细节和验货备注。",
          imageUrl: "/images/service/after-sales-review.png",
          alt: "售后团队核对问题证据与批次记录",
        },
        {
          title: "确认处理选项",
          body: "与客户确认可执行方案，包括补件、换货、补货、维修建议或费用沟通。",
          imageUrl: "/images/service/after-sales-fulfillment.png",
          alt: "为售后处理方案准备补件和订单资料",
        },
        {
          title: "完成并回访",
          body: "处理动作完成后归档结果，供客户复核，也用于后续生产、包装和验货改进。",
          imageUrl: "/images/service/after-sales-follow-up.png",
          alt: "售后结案回访与归档记录",
        },
      ],
      responseSteps: [
        {
          title: "发现问题",
          body: "整理图片、订单信息、批次记录和客户反馈，先把问题描述清楚。",
        },
        {
          title: "确认责任",
          body: "结合生产、包装、验货和运输信息，判断问题更可能发生在哪个环节。",
        },
        {
          title: "给出处理方案",
          body: "协调补件、补货、维修建议、费用沟通或下次订单的工艺修正。",
        },
      ],
    },
    newsletter: {
      title: "获取新品动态与专属优惠",
      body: "订阅产品更新、采购信息和专属优惠。",
      emailLabel: "邮箱地址",
      placeholder: "请输入您的邮箱地址",
      submit: "提交",
      success: "感谢订阅，我们会及时同步最新信息。",
    },
    trekkingPole: {
      eyebrow: "TP-AL-001",
      title: "铝合金登山杖",
      subtitle: "面向入门徒步场景的轻量双支装登山杖，兼顾稳定支撑、便携收纳与日常耐用性。",
      primaryCta: "咨询报价",
      secondaryCta: "查看参数",
      backToProducts: "返回产品中心",
      highlights: [
        "单支约 259 g",
        "51–110 cm 可调长度",
        "四节伸缩收纳",
        "隐藏式内锁",
      ],
      featureTitle: "为轻松、安心的徒步体验而设计。",
      featureBody:
        "TP-AL-001 在便携性、易调节和耐用材质之间取得平衡，适合新手徒步、零售配套和户外入门产品线。",
      specsTitle: "产品详情",
      specs: [
        { label: "材质", value: "铝合金杖身" },
        { label: "手柄", value: "TPR 直柄" },
        { label: "杖尖", value: "碳钢" },
        { label: "适用场景", value: "入门徒步" },
        { label: "配件", value: "泥托 + 杖尖保护套" },
        { label: "包装", value: "2 支装" },
      ],
    },
    about: {
      eyebrow: "关于我们",
      title: "让采购更稳定、更放心。",
      body: "Dawnrise Camp 面向海外客户提供露营装备开发、稳定生产与出口交付支持。",
      cta: "观看企业视频",
      videoError: "将企业视频上传到 R2 后，会在这里自动显示。",
      features: ["OEM / ODM 支持", "品质检验", "全球发运"],
      introSections: [
        {
          title: "公司介绍",
          body: "DawnRiseCamp 是一家专业户外产品品牌，致力于为全球客户提供可靠的露营、徒步和户外探险装备。凭借多年海外供货经验、严格质量控制和出货前二次检验，我们为全球批发商、经销商、零售商和电商卖家提供稳定的户外产品与灵活的 OEM / ODM 解决方案。",
          imageUrl: "/images/about/company-introduction.png",
          imageAlt: "准备检验和出口的露营户外装备样品",
        },
        {
          title: "品牌目标和服务理念",
          body: "我们的使命是为全球客户提供实用、耐用、可靠的户外产品。我们重视真实户外使用场景、稳定品质、快速响应服务，以及与商业伙伴建立长期合作关系。",
          imageUrl: "/images/about/brand-mission.png",
          imageAlt: "摆放露营装备和服务计划资料的户外工作台",
        },
        {
          title: "OEM / ODM 定制服务",
          body: "我们支持 OEM 与 ODM 服务，包括 logo 定制、包装设计、颜色选择、材料选择、尺寸调整和产品组合方案。无论您是批发商、经销商、零售商还是电商卖家，我们都可以协助您为目标市场建立定制化户外产品方案。",
          imageUrl: "/images/about/oem-odm-service.png",
          imageAlt: "包含材料、包装和色卡的户外产品开发工作台",
        },
      ],
      qualificationsEyebrow: "公司资质",
      qualificationsTitle: "公司资质",
      qualificationsBody: "资质材料围绕客户验厂、平台入驻、贸易合作和采购审核进行整理。",
      qualifications: [
        {
          title: "营业执照",
          body: "提供公司主体、经营范围等基础信息，便于客户进行合作前审核。",
          imageUrl: "/images/about/qualifications/business-license.png",
          imageAlt: "营业执照资料缩略图",
          badge: "已核验",
          updatedLabel: "更新状态",
          availability: "可供客户审核",
        },
        {
          title: "出口资料",
          body: "围绕报关、运输和海外客户复核，配合整理出口交付相关文件。",
          imageUrl: "/images/about/qualifications/export-records.png",
          imageAlt: "出口资料缩略图",
          badge: "已核验",
          updatedLabel: "更新状态",
          availability: "可供客户审核",
        },
        {
          title: "供应链信息",
          body: "根据产品线和订单需求，匹配工厂、生产与供应商协同信息。",
          imageUrl: "/images/about/qualifications/factory-coordination.png",
          imageAlt: "供应链协同资料缩略图",
          badge: "已核验",
          updatedLabel: "更新状态",
          availability: "可供客户审核",
        },
      ],
      qualificationsPanel: {
        title: "采购审核资料包",
        body: "核心资质材料按客户审核习惯整理，便于在打样或大货前快速确认公司主体、出口交付和供应链协同能力。",
        items: ["公司主体资料", "出口交付记录", "供应商协同信息"],
      },
      reportsEyebrow: "检测报告",
      reportsTitle: "检测报告",
      reportsBody: "可根据产品品类、材料、目标市场和平台要求，准备或更新对应检测资料。",
      reports: [
        {
          label: "材料",
          title: "材料与面料检测",
          body: "针对面料、涂层、色牢度等关键材料项目，按产品类别安排检测。",
          imageUrl: "/images/about/reports/material-fabric-checks.png",
          imageAlt: "材料与面料检测报告缩略图",
        },
        {
          label: "安全",
          title: "结构与承重测试",
          body: "围绕露营家具和户外装备，支持承重、稳定性、组装和重复使用测试。",
          imageUrl: "/images/about/reports/structure-load-testing.png",
          imageAlt: "结构与承重测试报告缩略图",
        },
        {
          label: "市场",
          title: "目标市场合规支持",
          body: "出货前可按目标市场和平台准入要求，配合整理检测报告和资料。",
          imageUrl: "/images/about/reports/market-compliance-support.png",
          imageAlt: "目标市场合规报告缩略图",
        },
      ],
    },
    quality: {
      eyebrow: "品质保障",
      title: "严格复检，安心出发。",
      subtitle:
        "每件产品在生产完成后都会再次检验，只有符合 DawnRiseCamp 品牌标准后才会批准出货。",
      processTitle: "质量控制流程",
      reportsTitle: "二次检验报告",
      qualificationsTitle: "公司资质",
      process: [
        {
          title: "材料复核",
          body: "根据已确认订单要求，检查面料、框架、五金、涂层和核心部件。",
        },
        {
          title: "生产检查",
          body: "在生产阶段跟进工艺、组装细节、尺寸和包装一致性。",
        },
        {
          title: "二次检验",
          body: "生产完成后再次检查成品，确认批次达到出货要求。",
        },
        {
          title: "报告记录",
          body: "整理检验备注、照片和问题记录，方便买家清晰复核出货状态。",
        },
        {
          title: "出货批准",
          body: "只有产品、包装和订单细节均符合 DawnRiseCamp 标准后，才安排放行出货。",
        },
      ],
      reports: [
        {
          label: "材料",
          title: "材料与面料检测",
          body: "针对面料、涂层、色牢度等关键材料项目，按产品类别安排检测。",
          imageUrl: "/images/about/reports/material-fabric-checks.png",
          imageAlt: "材料与面料检测报告缩略图",
        },
        {
          label: "安全",
          title: "结构与承重测试",
          body: "围绕露营家具和户外装备，支持承重、稳定性、组装和重复使用测试。",
          imageUrl: "/images/about/reports/structure-load-testing.png",
          imageAlt: "结构与承重测试报告缩略图",
        },
        {
          label: "市场",
          title: "目标市场合规支持",
          body: "出货前可按目标市场和平台准入要求，配合整理检测报告和资料。",
          imageUrl: "/images/about/reports/market-compliance-support.png",
          imageAlt: "目标市场合规报告缩略图",
        },
      ],
      qualifications: [
        {
          title: "营业执照",
          body: "提供公司主体、经营范围等基础信息，便于客户进行合作前审核。",
          imageUrl: "/images/about/qualifications/business-license.png",
          imageAlt: "营业执照资料缩略图",
          badge: "已核验",
        },
        {
          title: "出口资料",
          body: "围绕报关、运输和海外客户复核，配合整理出口交付相关文件。",
          imageUrl: "/images/about/qualifications/export-records.png",
          imageAlt: "出口资料缩略图",
          badge: "已核验",
        },
        {
          title: "供应链信息",
          body: "根据产品线和订单需求，匹配工厂、生产与供应商协同信息。",
          imageUrl: "/images/about/qualifications/factory-coordination.png",
          imageAlt: "供应链协同资料缩略图",
          badge: "已核验",
        },
      ],
    },
    products: {
      eyebrow: "产品",
      title: "产品分类",
      cta: "索取产品目录",
      productLinesLabel: "个产品系列",
      partOfLabel: "所属分类：",
      searchPlaceholder: "搜索产品或分类",
      noResults: "没有找到匹配的产品。",
      genericSubtitle: "面向采购项目、零售组合与出口交付需求的可靠户外产品系列。",
      genericPrimaryCta: "咨询报价",
      genericBackCta: "返回产品中心",
    },
    news: {
      eyebrow: "行业洞察",
      title: "户外产品趋势与采购洞察。",
      readMore: "查看详情",
      backToNews: "返回行业洞察",
    },
    contact: {
      eyebrow: "联系我们",
      title: "期待听到您的需求",
      body: "无论您正在开发户外新品、筛选供应商，还是准备批量订单，我们都可以协助您推进。所有询盘将在 24 小时内回复。",
      emailLabel: "邮箱",
      phoneLabel: "电话",
      phone: "+86 571 8888 6688",
      addressLabel: "办公地址",
      address: "中国浙江省杭州市余杭区运河路 88 号",
      hoursLabel: "工作时间",
      hours: "周一至周五 · 09:00–18:00",
      supportItems: [
        { title: "产品咨询", note: "请发送邮件至", email: "sales@dawnrisecamp.com" },
        { title: "订单支持", note: "请发送邮件至", email: "sales@dawnrisecamp.com" },
        { title: "商务合作", note: "请发送邮件至", email: "sales@dawnrisecamp.com" },
      ],
      mapTitle: "到访 Dawnrise Camp",
      mapCta: "打开地图",
      name: "姓名",
      email: "邮箱",
      company: "公司",
      message: "请详细描述您的需求",
      submit: "发送询盘",
      submitting: "发送中...",
      success: "询盘已发送，我们会尽快回复您。",
      error: "提交失败，请稍后重试。",
    },
    footer: {
      promise: "为全球买家提供可靠的户外产品。",
    },
  },
} satisfies Record<Locale, unknown>;

export const fallbackProducts: Record<Locale, ProductNode[]> = {
  en: [
    {
      slug: "tents-shelter-systems",
      name: "Tents & Shelter",
      children: [
        { slug: "camping-tarps", name: "Camping Tarps", children: [] },
        { slug: "car-awnings", name: "Car Awnings", children: [] },
      ],
    },
    {
      slug: "camping-sleep-systems",
      name: "Sleep Systems",
      children: [
        { slug: "inflatable-sleeping-pads", name: "Inflatable Sleeping Pads", children: [] },
        { slug: "camping-cots", name: "Camping Cots", children: [] },
      ],
    },
    {
      slug: "camping-furniture-accessories",
      name: "Furniture & Accessories",
      children: [
        { slug: "folding-camping-chairs", name: "Folding Camping Chairs", children: [] },
        { slug: "folding-camping-tables", name: "Folding Camping Tables", children: [] },
      ],
    },
    {
      slug: "camping-wagons-utility-carts",
      name: "Wagons & Utility Carts",
      children: [{ slug: "camping-wagons", name: "Camping Wagons", children: [] }],
    },
    {
      slug: "camp-kitchen-hydration-gear",
      name: "Camp Kitchen & Hydration",
      children: [{ slug: "hard-cooler-boxes", name: "Hard Cooler Boxes", children: [] }],
    },
    {
      slug: "backpacks-storage-solutions",
      name: "Backpacks & Storage",
      children: [],
    },
    {
      slug: "outdoor-lighting-utility-tools",
      name: "Lighting & Utility Tools",
      children: [],
    },
    {
      slug: "hiking-trekking-gear",
      name: "Hiking & Trekking Gear",
      children: [{ slug: "trekking-poles", name: "Trekking Poles", children: [] }],
    },
  ],
  zh: [
    {
      slug: "tents-shelter-systems",
      name: "帐篷与遮蔽系统",
      children: [
        { slug: "camping-tarps", name: "露营天幕", children: [] },
        { slug: "car-awnings", name: "车边帐", children: [] },
      ],
    },
    {
      slug: "camping-sleep-systems",
      name: "露营睡眠系统",
      children: [
        { slug: "inflatable-sleeping-pads", name: "充气睡垫", children: [] },
        { slug: "camping-cots", name: "露营行军床", children: [] },
      ],
    },
    {
      slug: "camping-furniture-accessories",
      name: "露营家具与配件",
      children: [
        { slug: "folding-camping-chairs", name: "折叠露营椅", children: [] },
        { slug: "folding-camping-tables", name: "折叠露营桌", children: [] },
      ],
    },
    {
      slug: "camping-wagons-utility-carts",
      name: "露营拖车与工具车",
      children: [{ slug: "camping-wagons", name: "露营拖车", children: [] }],
    },
    {
      slug: "camp-kitchen-hydration-gear",
      name: "营地厨房与饮水装备",
      children: [{ slug: "hard-cooler-boxes", name: "硬壳保温箱", children: [] }],
    },
    {
      slug: "backpacks-storage-solutions",
      name: "背包与收纳解决方案",
      children: [],
    },
    {
      slug: "outdoor-lighting-utility-tools",
      name: "户外照明与实用工具",
      children: [],
    },
    {
      slug: "hiking-trekking-gear",
      name: "徒步与登山装备",
      children: [{ slug: "trekking-poles", name: "登山杖", children: [] }],
    },
  ],
};

export const productProfiles: Record<Locale, Record<string, ProductProfile>> = {
  en: {
    "camping-wagons": {
      slug: "camping-wagons",
      code: "WG-FD-220",
      subtitle: "A foldable utility wagon built for smoother hauling across campsites, beaches, and family trips.",
      highlights: ["120 kg load rating", "All-terrain wheels", "Quick-fold frame", "Removable liner"],
      featureTitle: "More carrying capacity, less effort.",
      featureBody:
        "WG-FD-220 balances rugged transport with compact storage, making it a versatile line for campsite logistics and outdoor retail assortments.",
      specs: [
        { label: "Frame", value: "Powder-coated steel" },
        { label: "Fabric", value: "600D polyester" },
        { label: "Capacity", value: "120 kg" },
        { label: "Wheel", value: "Wide PU all-terrain wheels" },
      ],
      gallery: {
        lifestyle: "/images/products/camping-wagons-lifestyle.webp",
        studio: "/images/products/camping-wagons-studio.webp",
      },
    },
    "folding-camping-chairs": {
      slug: "folding-camping-chairs",
      code: "CH-LW-018",
      subtitle: "A refined low chair for relaxed camping, outdoor events, and premium leisure collections.",
      highlights: ["Walnut-tone armrests", "Compact fold", "Comfort seat angle", "Retail-ready styling"],
      featureTitle: "Comfort that looks considered.",
      featureBody:
        "CH-LW-018 gives a familiar outdoor staple a more polished posture, pairing practical portability with a warmer furniture-like feel.",
      specs: [
        { label: "Frame", value: "Steel tube" },
        { label: "Seat", value: "Canvas fabric" },
        { label: "Armrest", value: "Wood-look composite" },
        { label: "Best use", value: "Leisure camping" },
      ],
      gallery: {
        lifestyle: "/images/products/folding-camping-chairs-lifestyle.webp",
        studio: "/images/products/folding-camping-chairs-studio.webp",
      },
    },
    "inflatable-sleeping-pads": {
      slug: "inflatable-sleeping-pads",
      code: "SP-SI-040",
      subtitle: "A self-inflating sleeping pad designed for better campsite comfort without bulky packing.",
      highlights: ["Self-inflating core", "Compact carry sack", "Ribbed support surface", "Easy campsite setup"],
      featureTitle: "A softer night, packed smaller.",
      featureBody:
        "SP-SI-040 is tuned for practical comfort, helping buyers offer an accessible sleep upgrade for car camping and light travel programs.",
      specs: [
        { label: "Construction", value: "Foam-core self-inflating" },
        { label: "Surface", value: "Ribbed polyester" },
        { label: "Valve", value: "Single quick-release valve" },
        { label: "Best use", value: "Camping sleep systems" },
      ],
      gallery: {
        lifestyle: "/images/products/inflatable-sleeping-pads-lifestyle.webp",
        studio: "/images/products/inflatable-sleeping-pads-studio.webp",
      },
    },
    "camping-cots": {
      slug: "camping-cots",
      code: "CT-AL-090",
      subtitle: "A compact camping cot that keeps sleep surfaces elevated, stable, and easy to pack.",
      highlights: ["Elevated sleep deck", "Aluminum support frame", "Fast assembly", "Compact carry size"],
      featureTitle: "Stable rest above uneven ground.",
      featureBody:
        "CT-AL-090 gives campsites a cleaner, more structured sleep setup while staying manageable for storage and transport.",
      specs: [
        { label: "Frame", value: "Aluminum alloy" },
        { label: "Fabric", value: "Oxford polyester" },
        { label: "Load", value: "150 kg" },
        { label: "Pack", value: "Carry bag included" },
      ],
      gallery: {
        lifestyle: "/images/products/camping-cots-lifestyle.webp",
        studio: "/images/products/camping-cots-studio.webp",
      },
    },
    "camping-tarps": {
      slug: "camping-tarps",
      code: "TP-SH-300",
      subtitle: "A versatile tarp shelter for shade, rain coverage, and adaptable campsite layouts.",
      highlights: ["Large shade area", "Reinforced corners", "Multi-pitch setup", "Weather-ready fabric"],
      featureTitle: "One shelter, many camp layouts.",
      featureBody:
        "TP-SH-300 supports flexible pitching styles, giving outdoor assortments a highly usable shelter product with broad seasonal appeal.",
      specs: [
        { label: "Fabric", value: "150D ripstop polyester" },
        { label: "Coating", value: "PU waterproof coating" },
        { label: "Corners", value: "Reinforced webbing loops" },
        { label: "Best use", value: "Shade and rain cover" },
      ],
      gallery: {
        lifestyle: "/images/products/camping-tarps-lifestyle.webp",
        studio: "/images/products/camping-tarps-studio.webp",
      },
    },
    "car-awnings": {
      slug: "car-awnings",
      code: "AW-VE-250",
      subtitle: "A vehicle-mounted awning for fast roadside shade and simple overland camp setups.",
      highlights: ["Vehicle mount", "Quick deployment", "Integrated storage sleeve", "Road-trip friendly"],
      featureTitle: "Shade that travels with the vehicle.",
      featureBody:
        "AW-VE-250 extends usable camp space in minutes, making it a strong option for overland and automotive outdoor lines.",
      specs: [
        { label: "Mount", value: "Roof rack compatible" },
        { label: "Canopy", value: "Ripstop polyester" },
        { label: "Frame", value: "Aluminum support arms" },
        { label: "Best use", value: "Vehicle camping" },
      ],
      gallery: {
        lifestyle: "/images/products/car-awnings-lifestyle.webp",
        studio: "/images/products/car-awnings-studio.webp",
      },
    },
    "folding-camping-tables": {
      slug: "folding-camping-tables",
      code: "TB-RL-060",
      subtitle: "A compact roll-top table for camp kitchens, coffee setups, and lightweight outdoor dining.",
      highlights: ["Roll-top surface", "Fast pack-down", "Stable cross frame", "Warm tabletop finish"],
      featureTitle: "A small table that earns its footprint.",
      featureBody:
        "TB-RL-060 brings structure to campsite routines without adding visual weight, making it easy to pair with chairs and kitchen accessories.",
      specs: [
        { label: "Top", value: "Roll-top aluminum slats" },
        { label: "Frame", value: "Powder-coated steel" },
        { label: "Assembly", value: "Tool-free" },
        { label: "Best use", value: "Camp dining and prep" },
      ],
      gallery: {
        lifestyle: "/images/products/folding-camping-tables-lifestyle.webp",
        studio: "/images/products/folding-camping-tables-studio.webp",
      },
    },
    "hard-cooler-boxes": {
      slug: "hard-cooler-boxes",
      code: "CL-HD-035",
      subtitle: "A rugged hard cooler for chilled storage across camping, picnic, and overland use.",
      highlights: ["35 L capacity", "Heavy-duty latches", "Textured grip lid", "Long-hold insulation"],
      featureTitle: "Built to keep essentials colder, longer.",
      featureBody:
        "CL-HD-035 adds a durable utility anchor to the assortment, suited to campsites, road trips, and practical outdoor bundles.",
      specs: [
        { label: "Capacity", value: "35 L" },
        { label: "Shell", value: "Rotomolded polyethylene" },
        { label: "Latch", value: "Rubber T-latch" },
        { label: "Best use", value: "Food and drink storage" },
      ],
      gallery: {
        lifestyle: "/images/products/hard-cooler-boxes-lifestyle.webp",
        studio: "/images/products/hard-cooler-boxes-studio.webp",
      },
    },
  },
  zh: {
    "camping-wagons": {
      slug: "camping-wagons",
      code: "WG-FD-220",
      subtitle: "适用于营地、海滩与家庭出游的折叠运输拖车，兼顾承载力与便携收纳。",
      highlights: ["120 kg 承重", "全地形宽轮", "快速折叠", "可拆洗内衬"],
      featureTitle: "装得更多，拖得更轻松。",
      featureBody: "WG-FD-220 在大容量运输和紧凑收纳之间取得平衡，适合营地搬运与户外零售组合。",
      specs: [
        { label: "车架", value: "喷粉钢管" },
        { label: "面料", value: "600D 涤纶" },
        { label: "承重", value: "120 kg" },
        { label: "车轮", value: "宽幅 PU 全地形轮" },
      ],
      gallery: {
        lifestyle: "/images/products/camping-wagons-lifestyle.webp",
        studio: "/images/products/camping-wagons-studio.webp",
      },
    },
    "folding-camping-chairs": {
      slug: "folding-camping-chairs",
      code: "CH-LW-018",
      subtitle: "适合休闲露营、户外活动与精品陈列的低座折叠椅。",
      highlights: ["木纹扶手", "便携折叠", "舒适坐姿", "更适合零售陈列"],
      featureTitle: "把舒适和质感放在一起。",
      featureBody: "CH-LW-018 让高频户外单品拥有更克制的家具感，兼顾便携性与更好的视觉完成度。",
      specs: [
        { label: "框架", value: "钢管" },
        { label: "坐面", value: "帆布面料" },
        { label: "扶手", value: "木纹复合材质" },
        { label: "适用场景", value: "休闲露营" },
      ],
      gallery: {
        lifestyle: "/images/products/folding-camping-chairs-lifestyle.webp",
        studio: "/images/products/folding-camping-chairs-studio.webp",
      },
    },
    "inflatable-sleeping-pads": {
      slug: "inflatable-sleeping-pads",
      code: "SP-SI-040",
      subtitle: "兼顾舒适度与收纳体积的自充气睡垫，适合基础露营睡眠系统。",
      highlights: ["自充气结构", "便携收纳袋", "波纹支撑面", "快速铺设"],
      featureTitle: "睡得更舒服，带得更轻巧。",
      featureBody: "SP-SI-040 为自驾露营和轻量出行提供更容易接受的舒适升级。",
      specs: [
        { label: "结构", value: "泡棉自充气" },
        { label: "表面", value: "波纹涤纶" },
        { label: "气阀", value: "单个快放气阀" },
        { label: "适用场景", value: "露营睡眠系统" },
      ],
      gallery: {
        lifestyle: "/images/products/inflatable-sleeping-pads-lifestyle.webp",
        studio: "/images/products/inflatable-sleeping-pads-studio.webp",
      },
    },
    "camping-cots": {
      slug: "camping-cots",
      code: "CT-AL-090",
      subtitle: "让睡眠面离地、更稳定、也更易收纳的便携行军床。",
      highlights: ["离地睡眠", "铝合金支架", "快速组装", "紧凑收纳"],
      featureTitle: "在不平整地面上，也能睡得更稳。",
      featureBody: "CT-AL-090 让营地睡眠更整洁有序，同时保持较好的运输与储存效率。",
      specs: [
        { label: "框架", value: "铝合金" },
        { label: "床面", value: "牛津布" },
        { label: "承重", value: "150 kg" },
        { label: "包装", value: "含便携收纳袋" },
      ],
      gallery: {
        lifestyle: "/images/products/camping-cots-lifestyle.webp",
        studio: "/images/products/camping-cots-studio.webp",
      },
    },
    "camping-tarps": {
      slug: "camping-tarps",
      code: "TP-SH-300",
      subtitle: "适用于遮阳、防雨与多种搭建方式的露营天幕。",
      highlights: ["大面积遮蔽", "加固角位", "多种搭建", "防雨面料"],
      featureTitle: "一顶天幕，适配更多营地布局。",
      featureBody: "TP-SH-300 具备灵活搭建能力，是覆盖季节更广、适配性更强的营地遮蔽产品。",
      specs: [
        { label: "面料", value: "150D 防撕裂涤纶" },
        { label: "涂层", value: "PU 防水涂层" },
        { label: "角位", value: "加固织带环" },
        { label: "适用场景", value: "遮阳与防雨" },
      ],
      gallery: {
        lifestyle: "/images/products/camping-tarps-lifestyle.webp",
        studio: "/images/products/camping-tarps-studio.webp",
      },
    },
    "car-awnings": {
      slug: "car-awnings",
      code: "AW-VE-250",
      subtitle: "为车载露营与自驾场景准备的快速展开式车边帐。",
      highlights: ["车顶安装", "快速展开", "一体式收纳套", "适合自驾露营"],
      featureTitle: "跟着车辆一起移动的阴凉。",
      featureBody: "AW-VE-250 可在短时间内扩展营地可用空间，是车载户外产品线里的高辨识度单品。",
      specs: [
        { label: "安装", value: "兼容车顶行李架" },
        { label: "篷布", value: "防撕裂涤纶" },
        { label: "支架", value: "铝合金支撑臂" },
        { label: "适用场景", value: "车载露营" },
      ],
      gallery: {
        lifestyle: "/images/products/car-awnings-lifestyle.webp",
        studio: "/images/products/car-awnings-studio.webp",
      },
    },
    "folding-camping-tables": {
      slug: "folding-camping-tables",
      code: "TB-RL-060",
      subtitle: "适合营地厨房、咖啡冲煮和轻量餐食场景的便携卷桌。",
      highlights: ["卷式桌面", "快速收纳", "稳定交叉支架", "温润木色"],
      featureTitle: "占地不大，却很有用。",
      featureBody: "TB-RL-060 让营地生活更有秩序，也更容易与椅子、厨房配件形成完整组合。",
      specs: [
        { label: "桌面", value: "卷式铝片桌面" },
        { label: "框架", value: "喷粉钢架" },
        { label: "组装", value: "免工具" },
        { label: "适用场景", value: "营地用餐与备餐" },
      ],
      gallery: {
        lifestyle: "/images/products/folding-camping-tables-lifestyle.webp",
        studio: "/images/products/folding-camping-tables-studio.webp",
      },
    },
    "hard-cooler-boxes": {
      slug: "hard-cooler-boxes",
      code: "CL-HD-035",
      subtitle: "适用于露营、野餐与自驾场景的耐用硬壳保温箱。",
      highlights: ["35 L 容量", "重型锁扣", "防滑箱盖", "长效保冷"],
      featureTitle: "让重要补给保持更久的新鲜。",
      featureBody: "CL-HD-035 为产品线补上了耐用、实用且适合组合销售的营地储冷单品。",
      specs: [
        { label: "容量", value: "35 L" },
        { label: "箱体", value: "滚塑聚乙烯" },
        { label: "锁扣", value: "橡胶 T 型锁扣" },
        { label: "适用场景", value: "食物与饮品保冷" },
      ],
      gallery: {
        lifestyle: "/images/products/hard-cooler-boxes-lifestyle.webp",
        studio: "/images/products/hard-cooler-boxes-studio.webp",
      },
    },
  },
};

export const fallbackNews: Record<Locale, NewsItem[]> = {
  en: [
    {
      slug: "camping-furniture-sourcing-2026",
      publishedAt: "2026-05-12",
      title: "Camping Furniture Sourcing: What Buyers Are Checking in 2026",
      excerpt:
        "Retail buyers are looking more closely at foldability, fabric strength, carton efficiency, and secondary inspection records.",
      imageUrl: "/images/news-furniture.webp",
      body: [
        "Camping furniture remains a practical anchor category for outdoor retail programs. Buyers are paying attention to how chairs, tables, cots, and wagons perform after repeated folding, packing, and transport.",
        "For export orders, the most useful checks include frame stability, fabric tension, coating consistency, carton drop resistance, and clear replacement-part handling. These details help reduce after-sales uncertainty once products enter overseas channels.",
      ],
    },
    {
      slug: "shelter-systems-buyer-checklist-2026",
      publishedAt: "2026-02-18",
      title: "A Buyer Checklist for Tents, Tarps, and Shelter Accessories",
      excerpt:
        "Shelter programs benefit from early checks on fabric coating, pole strength, stitching, accessories, and setup instructions.",
      imageUrl: "/images/products.webp",
      body: [
        "Tents and shelter systems involve more small details than many buyers expect. Fabric, seams, zippers, poles, guy ropes, stakes, and packaging all affect the final customer experience.",
        "A clear checklist before bulk production helps align product expectations and makes secondary inspection faster after production is complete.",
      ],
    },
    {
      slug: "wagon-capacity-update",
      publishedAt: "2025-10-09",
      title: "How Camping Wagons Became a Core Outdoor Utility Product",
      excerpt:
        "Camping wagons support campsites, beaches, gardens, and family trips, making them a flexible category for many retail channels.",
      imageUrl: "/images/news-wagons.webp",
      body: [
        "Camping wagons have moved beyond a single camping use case. Their value comes from practical hauling, easy storage, and broad seasonal demand.",
        "For sourcing teams, wheel structure, fabric denier, frame coating, folding action, and load testing are key factors to confirm before shipment approval.",
      ],
    },
    {
      slug: "oem-odm-outdoor-packaging-2025",
      publishedAt: "2025-04-16",
      title: "OEM / ODM Packaging Details That Improve Outdoor Product Programs",
      excerpt:
        "Logo placement, carton structure, instruction inserts, and bundled accessories can make outdoor product lines easier to sell and support.",
      imageUrl: "/images/news-furniture.webp",
      body: [
        "Packaging is often where product development becomes market-ready. For outdoor gear, packaging must protect the product while keeping retail presentation and shipping efficiency in balance.",
        "OEM and ODM programs should confirm logo position, color standards, carton markings, accessory lists, and instruction language before mass production.",
      ],
    },
    {
      slug: "camping-sleep-systems-2024",
      publishedAt: "2024-09-20",
      title: "Camping Sleep Systems: Comfort, Pack Size, and Quality Control",
      excerpt:
        "Sleeping pads and camping cots need a balance of comfort, portability, material consistency, and reliable load performance.",
      imageUrl: "/images/products.webp",
      body: [
        "Sleep products are judged quickly by end users. Surface comfort, inflation behavior, frame stability, and carry size all influence repeat purchase potential.",
        "Quality checks should include sample comparison, load review, valve function, fabric surface inspection, and packing confirmation.",
      ],
    },
    {
      slug: "outdoor-material-selection-2024",
      publishedAt: "2024-03-14",
      title: "Material Selection Notes for Outdoor Gear Buyers",
      excerpt:
        "Fabric, coating, metal hardware, and plastic components should be selected according to the target use scenario and price band.",
      imageUrl: "/images/news-furniture.webp",
      body: [
        "Outdoor products face abrasion, sun exposure, moisture, and repeated handling. Material selection should start from the real use scenario instead of only a target price.",
        "When buyers define the expected market position early, suppliers can recommend more practical fabric, frame, coating, and accessory combinations.",
      ],
    },
    {
      slug: "tarps-canopies-market-2023",
      publishedAt: "2023-11-06",
      title: "Why Tarps and Canopies Work Well in Seasonal Outdoor Assortments",
      excerpt:
        "Shelter products are easy to combine with tents, chairs, tables, and camp kitchen items for flexible outdoor retail programs.",
      imageUrl: "/images/products.webp",
      body: [
        "Tarps and canopies are useful because they fit many outdoor scenes, including campsites, beaches, gardens, festivals, and vehicle travel.",
        "For product planning, buyers should compare setup method, packed size, waterproofing, UV resistance, attachment points, and included accessories.",
      ],
    },
    {
      slug: "secondary-inspection-2023",
      publishedAt: "2023-05-23",
      title: "What Secondary Inspection Adds Before Outdoor Gear Shipment",
      excerpt:
        "A second inspection after production helps catch workmanship, packing, and order-detail issues before goods leave the factory.",
      imageUrl: "/images/news-wagons.webp",
      body: [
        "Secondary inspection is most useful when it is tied to confirmed order standards. It checks finished goods after production instead of relying only on in-process review.",
        "For outdoor products, this step can cover appearance, structure, accessory completeness, carton marks, and shipment readiness.",
      ],
    },
    {
      slug: "trekking-gear-entry-products-2022",
      publishedAt: "2022-08-17",
      title: "Entry-Level Trekking Gear for Retail Outdoor Programs",
      excerpt:
        "Trekking poles and compact hiking accessories give retailers accessible products for beginner outdoor customers.",
      imageUrl: "/images/products.webp",
      body: [
        "Beginner-friendly trekking products should feel simple, durable, and easy to understand. Clear specifications and stable quality matter more than overly complex feature claims.",
        "For trekking poles, buyers should review lock structure, handle material, tip quality, section fit, and packed pair presentation.",
      ],
    },
    {
      slug: "outdoor-retail-assortment-2022",
      publishedAt: "2022-03-10",
      title: "Building a Practical Outdoor Retail Assortment",
      excerpt:
        "A balanced camping assortment usually combines furniture, shelter, sleep, storage, lighting, and utility products.",
      imageUrl: "/images/news-furniture.webp",
      body: [
        "Outdoor assortments work best when products support each other. Chairs, tables, tents, tarps, cots, wagons, and coolers can be planned as a complete camping story.",
        "For sourcing, the goal is to combine reliable core products with flexible OEM / ODM options for different markets and channels.",
      ],
    },
  ],
  zh: [
    {
      slug: "camping-furniture-sourcing-2026",
      publishedAt: "2026-05-12",
      title: "2026 年露营家具采购关注点",
      excerpt: "海外买家更关注折叠结构、面料强度、装箱效率和二次检验记录。",
      imageUrl: "/images/news-furniture.webp",
      body: [
        "露营家具仍然是户外零售里的核心品类。椅子、桌子、行军床和拖车都需要经得起反复折叠、包装和运输。",
        "出口订单中，车架稳定性、面料张力、涂层一致性、纸箱抗摔和售后配件方案，都是更值得提前确认的细节。",
      ],
    },
    {
      slug: "shelter-systems-buyer-checklist-2026",
      publishedAt: "2026-02-18",
      title: "帐篷、天幕与遮蔽配件采购检查清单",
      excerpt: "遮蔽类产品应提前检查面料涂层、杆件强度、车缝、配件和说明书。",
      imageUrl: "/images/products.webp",
      body: [
        "帐篷与遮蔽系统包含的细节很多：面料、接缝、拉链、支架、风绳、地钉和包装都会影响最终用户体验。",
        "量产前建立清晰检查清单，可以让订单标准更明确，也能让出货前二次检验更高效。",
      ],
    },
    {
      slug: "wagon-capacity-update",
      publishedAt: "2025-10-09",
      title: "露营拖车为什么成为户外实用品类",
      excerpt: "露营拖车覆盖营地、海滩、庭院和家庭出游，是适配渠道很广的产品。",
      imageUrl: "/images/news-wagons.webp",
      body: [
        "露营拖车已经不只是单一露营产品，它的价值在于运输方便、收纳相对简单，并且适合多个季节销售。",
        "采购时应重点确认轮组结构、面料规格、车架涂层、折叠手感和承重测试。",
      ],
    },
    {
      slug: "oem-odm-outdoor-packaging-2025",
      publishedAt: "2025-04-16",
      title: "户外产品 OEM / ODM 包装细节",
      excerpt: "Logo、纸箱结构、说明书和配件组合，会直接影响产品销售与售后支持。",
      imageUrl: "/images/news-furniture.webp",
      body: [
        "包装是产品从样品走向市场的重要一步。户外产品包装既要保护产品，也要兼顾零售展示和运输效率。",
        "OEM / ODM 项目应在量产前确认 Logo 位置、颜色标准、箱唛、配件清单和说明书语言。",
      ],
    },
    {
      slug: "camping-sleep-systems-2024",
      publishedAt: "2024-09-20",
      title: "露营睡眠系统：舒适度、收纳与质检",
      excerpt: "睡垫和行军床需要平衡舒适、便携、材料一致性和承重表现。",
      imageUrl: "/images/products.webp",
      body: [
        "睡眠类产品很容易被用户直接评价。表面舒适度、充放气体验、支架稳定性和收纳尺寸都会影响复购。",
        "质量检查应覆盖样品对比、承重复核、气阀功能、面料表面和包装完整性。",
      ],
    },
    {
      slug: "outdoor-material-selection-2024",
      publishedAt: "2024-03-14",
      title: "户外装备材料选择建议",
      excerpt: "面料、涂层、五金和塑料件，应根据真实使用场景和目标价格带选择。",
      imageUrl: "/images/news-furniture.webp",
      body: [
        "户外产品会面对摩擦、日晒、潮湿和频繁搬运。材料选择应从真实使用场景出发，而不是只看目标价格。",
        "买家越早定义产品定位，供应商越容易推荐合适的面料、支架、涂层和配件组合。",
      ],
    },
    {
      slug: "tarps-canopies-market-2023",
      publishedAt: "2023-11-06",
      title: "天幕与遮阳棚为什么适合季节性户外组合",
      excerpt: "遮蔽产品可以和帐篷、椅子、桌子、营地厨房用品形成组合销售。",
      imageUrl: "/images/products.webp",
      body: [
        "天幕和遮阳棚适用于营地、海滩、庭院、活动和车载出行，使用场景非常广。",
        "规划产品时，应比较搭建方式、收纳尺寸、防水、防晒、挂点数量和随附配件。",
      ],
    },
    {
      slug: "secondary-inspection-2023",
      publishedAt: "2023-05-23",
      title: "户外产品出货前二次检验的价值",
      excerpt: "生产完成后的二次检验，有助于在出厂前发现工艺、包装和订单细节问题。",
      imageUrl: "/images/news-wagons.webp",
      body: [
        "二次检验需要围绕已确认的订单标准执行。它检查的是生产完成后的成品，而不是只依赖生产过程中的抽查。",
        "对户外产品来说，这一步可以覆盖外观、结构、配件完整性、箱唛和出货准备。",
      ],
    },
    {
      slug: "trekking-gear-entry-products-2022",
      publishedAt: "2022-08-17",
      title: "适合零售渠道的入门徒步装备",
      excerpt: "登山杖和轻量徒步配件，适合作为新手户外客户的入门产品。",
      imageUrl: "/images/products.webp",
      body: [
        "入门徒步产品应简单、耐用、容易理解。稳定品质和清晰规格，比复杂卖点更重要。",
        "以登山杖为例，采购时应检查锁紧结构、手柄材质、杖尖质量、分节配合和成对包装呈现。",
      ],
    },
    {
      slug: "outdoor-retail-assortment-2022",
      publishedAt: "2022-03-10",
      title: "如何建立实用的户外零售产品组合",
      excerpt: "均衡的露营产品组合通常包括家具、遮蔽、睡眠、收纳、照明和工具类产品。",
      imageUrl: "/images/news-furniture.webp",
      body: [
        "户外产品组合最好能互相支撑。椅子、桌子、帐篷、天幕、行军床、拖车和保温箱可以形成完整露营场景。",
        "采购时，应把稳定核心品类与灵活 OEM / ODM 方案结合起来，适配不同市场和渠道。",
      ],
    },
  ],
};
